### ISSUE TITLE
Signal failed error

### ISSUE THREAD

**Issue by agnelvishal** [dapphp/TorUtils#2]
I get an error in TorUtils-master/examples/tc_NewNym.php 
Signal failed: Dapphp\TorUtils\ProtocolError in TorUtils-master/src/ControlClient.php:751
Stack trace:
#0 TorUtils-master/examples/tc_NewNym.php(16): Dapphp\TorUtils\ControlClient->signal('NEWNYM')
#1 {main}

**Comment by dapphp** [comment]
What version of Tor are you running this against?  It looks like you're authenticating fine but sending that signal is returning an error (probably unsupported) but it's strange that it's catching the exception but printing the stack trace instead of the exception message.  It should just show something like:

    Signal failed: Unrecognized signal code "NEWNYM"

or some kind of specific reason why it failed.

**Comment by agnelvishal** [comment]
You are right. The error message was empty. Hence I printed the stack
trace.
Unfortunately I am out of town for 3 days. Hence will tell about tor
version later.
 Thanks for replying. Hoping to solve my long time problem.

**Comment by dapphp** [comment]
Okay, it might be an issue with the way the response is being parsed.  When you return, we can check the Tor version and also, it would help me fix the issue if you could modify tc_NewNym.php and make the following change:

Add `$tc->setDebug(true);` to the line right after `$tc = new ControlClient();`.  Then, when you run it we'll see the data sent to and from Tor.  Let me know what it shows (redact any password) and I can make sure things are getting parsed properly.

Thanks!

**Comment by agnelvishal** [comment]
Solved it. Messed up by commenting the Authentication code because I did not set any. Thanks :)

**Comment by dapphp** [comment]
Glad you figured it out.  Still strange the exception was empty.  If I comment out the authenticate line, I get `Signal failed: Authentication required.` and if I put the wrong password, `Signal failed: Authentication failed: Password did not match HashedControlPassword *or* authentication cookie.`

If you still think there might be an issue with not getting back a proper exception message, feel free to re-open and post the debug log so I can see what happened.

**Comment by dapphp** [comment]
Also, hopefully you're finding this useful.  If there's anything you're trying to do that it currently doesn't support and you have a suggestion, feel free to post a request!

**Comment by agnelvishal** [comment]
Right now I too get Signal failed: Authentication required if I comment it. Don't remember exactly what I did that day but I do remember doing something in ControlClient.php

**Comment by agnelvishal** [comment]
Will tell you if I have a suggestion, Nothing now

**Comment by bonnebulle** [comment]
I cant fix it using `$tc = new ControlClient();` + `$tc->setDebug(true);`, I would like to have full debug, right now I just have a 
> . Error: 111 - Connection refused

Am tring `tc_NewNym.php`
I have hashed my pasword and set cookies to 1.
Can you help ?
